apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.3
apiServer:
  extraArgs:
    service-node-port-range: 1-65535
  certSANs:
  - "49.65.2.37"
networking:
  podSubnet: 192.168.0.0/16
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

---

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.252.1.61
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 10.252.1.61

---

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs